### ISSUE TITLE
Author in `package.json` is `GitHub`

### ISSUE THREAD

**Issue by bnb** [actions/javascript-action#16]
If this is a template repository, the default for `author` in `package.json` should be empty since if used as a template by folks in the ecosystem `GitHub` will not be correct. If folks have npm configured, running `npm init` or `npm init -y` once cloned will enable them to be self-selecting on what the truth for this is.

Additionally, if documented, `npm init` were run this would enable them to immediately correct the name in the package.json, the version, and the license that they want to individually select.

**Comment by hross** [comment]
Fixed in https://github.com/actions/javascript-action/pull/36
