### ISSUE TITLE
Enable automatic dependency upgrades in this repository

### ISSUE THREAD

**Issue by bnb** [actions/javascript-action#17]
Given that this is intended to be an evergreen template, having automated dependency updates is super important to reduce maintainer burden _and_ downstream maintainer burden, reducing the number of upgrades they'll need to do out of the box.

I discovered that `jest@24.9.0` was outdated because I was being yelled at by `request` being deprecated, which seems to have been solved all the way up the tree in every dependency from jsdom which introduces it to `jest@25.1.0`.

**Comment by hross** [comment]
done here: https://github.com/actions/javascript-action/pull/37
