### ISSUE TITLE
action.yml - update runs.using to node14 or node16?

### ISSUE THREAD

**Issue by MSP-Greg** [actions/javascript-action#171]
Currently, actions.yml uses `runs.using: node12`, see below.  I believe all current Actions images use 16.13.1, and 12 is the oldest version installed?

https://github.com/actions/javascript-action/blob/c1c60989a13ec68893bc5ea614991fba4aab8644/action.yml#L1-L13

**Comment by dmitry-shibanov** [comment]
Hello @MSP-Greg. Thank you for your report. All of the first-party actions were switched to node16. The javascript-action was switched too. 
For now I'm going to close the issue. If you have any concerns feel free to ping us.
