### ISSUE TITLE
Potential security vulnerabilities in acorn and minimist

### ISSUE THREAD

**Issue by fniephaus** [actions/javascript-action#20]
It looks like acorn and minimist have security vulnerabilities:
- Upgrade acorn to version 5.7.4 or later (https://app.snyk.io/vuln/SNYK-JS-ACORN-559469)
- Upgrade minimist to version 1.2.2 or later (https://app.snyk.io/vuln/SNYK-JS-MINIMIST-559764)

Dependabot was able to upgrade acorn, but not minimist (*Dependabot cannot create a pull request as one or more other dependencies require a version that is incompatible with this update.*)

I'm not sure how to resolve this correctly, so please upgrade the dependencies of this template.

Many thanks,
Fabio

**Comment by hross** [comment]
thanks. looking into this.
