### ISSUE TITLE
Install npm modules automatically for node actions

### ISSUE THREAD

**Issue by danielkatz** [actions/javascript-action#3]
Currently, if the `node_modules` aren't included in the repo, the action will fail on `require('@actions/core')`.
This probably should be dealt with on the platform level, but in the mean time, `node_modules` shouldn't be excluded in the `.gitignore`.

**Comment by fabiankaegy** [comment]
just ran into the same thing and agree that this should be handled by the platform :)

**Comment by wesleytodd** [comment]
https://github.com/wesleytodd/actions-testing/commit/73159469ab560d08f64e59a61fbe64d65764057a/checks

I used the template, and then pushed a commit, the action ran fine.  Can you all who are seeing this issue provide more context?

**Comment by danielkatz** [comment]
> https://github.com/wesleytodd/actions-testing/commit/73159469ab560d08f64e59a61fbe64d65764057a/checks
> 
> I used the template, and then pushed a commit, the action ran fine. Can you all who are seeing this issue provide more context?

Since your action is in the same repo as the workflow, you can run `npm ci` on ***your*** action. This approach isn't applicable for published public actions.

**Comment by danielkatz** [comment]
> Another solution to not push node_modules into git is to use a bundler like webpack, parcel, etc

The same problem, if i'll use a bundler, i'll have to publish the **bundled** code to the repo.

**Comment by wesleytodd** [comment]
https://github.com/wesleytodd/actions-testing/commit/e0ca2a86035790823447e1288f722c1908b762e5/checks

This run was against this template.  And it also worked.

**Comment by danielkatz** [comment]
> https://github.com/wesleytodd/actions-testing/commit/e0ca2a86035790823447e1288f722c1908b762e5/checks
> 
> This run was against this template. And it also worked.

You as a **user** of an action can run `npm ci` to make it work. But as a **publisher** of an action, you can't run `npm ci` on your action because of syntax limitations, so you have to rely on the **user** to run it for you, which isn't the best UX...

**Comment by wesleytodd** [comment]
Ok, thanks I was able to reporduce:

https://github.com/wesleytodd/actions-testing/commit/7b6d9d97d9298bf57b07bdaab2f2c0956d11e85b/checks

**Comment by bryanmacfarlane** [comment]
You're referencing master which is the coding branch.  You should reference a distribution branch.  The distribution branch contains a fully self contained set of code.

https://github.com/actions/toolkit/blob/master/docs/action-versioning.md

This template and walkthrough has you checking in production dependencies.  

**The runner downloads the files at the location and ref and runs it.  That's it.**

In the example above ^^ you're referencing master which is the coding branch and doesn't have production runtime dependencies.

npm install is a dev build time action.  distributions are self contained.

covered in readme walthrough: https://github.com/actions/javascript-action#publish-to-a-distribution-branch

**Comment by bryanmacfarlane** [comment]
The requirement is to be able to reference the distribution to run by an immutable reference (sha) or ref.

We have an enhancement that we're targetting hopefully for later this year where a workflow can reference from GPR (packaging)

**Comment by bryanmacfarlane** [comment]
Until we get to GPR, we found a better mitigated solution.  https://github.com/actions/javascript-action/pull/5
