### ISSUE TITLE
Look for maintainers?

### ISSUE THREAD

**Issue by OmgImAlexis** [actions/javascript-action#30]
This repos seems to have been abandoned since it was created. If GitHub isn't going to maintain this can we please have someone community members added to the team so they can handle PRs, etc.

PING: @bryanmacfarlane

**Comment by wesleytodd** [comment]
I think there is just not much to do on it and they are a bit slow to respond.  Are there things which you think should have been merged/done recently?  There are a few PRs which are open (one of mine 😄!), but nothing super pressing IMO.

**Comment by hross** [comment]
Thanks for the ping here. We will try to give this repo a bit more attention but yes... we are slow to update this repo because there is nothing high priority here at the moment.
