### ISSUE TITLE
Test comment headers outdated?

### ISSUE THREAD

**Issue by benabineri** [actions/javascript-action#340]
This repo has already been really useful for developing an action from scratch - I see it's being actively developed again which is great.

The header comments on the test files seem to be outdated now - they mention `.ts` files, and the main one mentions setting inputs as environment variables:

```
/**
 * Unit tests for the action's main functionality, src/main.ts
 *
 * These should be run as if the action was called from a workflow.
 * Specifically, the inputs listed in `action.yml` should be set as environment
 * variables following the pattern `INPUT_<INPUT_NAME>`.
 */
 ```
 
 However as far as I can tell this isn't necessary, is that right?

**Comment by ncalteen** [comment]
Thanks for the catch there! This was likely because the comments were copied over from [`actions/typescript-action`](https://github.com/actions/typescript-action). I'll update them and submit a PR shortly.
