### ISSUE TITLE
Add development containers for GitHub Codespaces

### ISSUE THREAD

**Issue by RyanLua** [actions/javascript-action#382]
When you open a GitHub Codespace for this repository, you must install dependencies and test for errors. This process could be improved using [dev containers](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers).

With a proper dev container setup, you could have all the dependencies and tests run already so you don't have to do that process every time you open a codespace. In addition, you can have Visual Studio Code extensions pre-installed into codespaces.

**Comment by ncalteen** [comment]
I think this is a great idea :) There are a few template repos that could use this in the org. I'll take a look at this soon!
