### ISSUE TITLE
Issue with linting when executed on push

### ISSUE THREAD

**Issue by karpikpl** [actions/javascript-action#391]
I've created a new repository using this template and the linting action failed when executed on a branch (it worked on a PR)

The error `Failed to initialize GITHUB_BEFORE_SHA for a push event. Output: HEAD~2` indicates that there's an issue with checkout but it's executed with `fetch-depth: 0` as recommended (I also did not change anything in the workflows).

Here's the link to failing action: https://github.com/karpikpl/linting-issue/actions/runs/8376693852/job/22936968104

Steps to reproduce:
1. Use template
2. Wait for the linting to run

**Comment by ncalteen** [comment]
I took a look at the [`super-linter/super-linter`](https://github.com/super-linter/super-linter) repo to see if there is a known issue related to this. It looks like this was previously a [known issue](https://github.com/super-linter/super-linter/issues/5239).

Out of curiosity, I tried a couple different permutations of settings, with the results below:

| Action Version                          | `VALIDATE_ALL_CODEBASE` | Results                                                                                       |
| --------------------------------------- | ----------------------- | --------------------------------------------------------------------------------------------- |
| `super-linter/super-linter/slim@v6.3.0` | `true`                  | [Same Error](https://github.com/ncalteen/linter-test/actions/runs/8482337223/job/23241391159) |
| `super-linter/super-linter/slim@v6.3.0` | `false`                 | [Same Error](https://github.com/ncalteen/linter-test/actions/runs/8482337225/job/23241390928) |
| `super-linter/super-linter@v6.3.0`      | `true`                  | [Same Error](https://github.com/ncalteen/linter-test/actions/runs/8482337231/job/23241391370) |
| `super-linter/super-linter@v6.3.0`      | `false`                 | [Same Error](https://github.com/ncalteen/linter-test/actions/runs/8482337259/job/23241391335) |

So I think it's safe to assume the issue has not been resolved. I will open an issue in their repo to get guidance :)

**Comment by ncalteen** [comment]
Issue created: https://github.com/super-linter/super-linter/issues/5453

**Comment by karpikpl** [comment]
thanks @ncalteen !

**Comment by ncalteen** [comment]
Heyo @karpikpl, I am going to close this out since it is not related to this repo itself, but the SuperLinter action.
